# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('room_no', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('purpose', models.TextField(max_length=500)),
            ],
        ),
    ]
