# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attsheet',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
