# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-24 18:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0003_attsheet_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='attsheet',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attsheet',
            name='remarks',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='attsheet',
            name='room_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
